[versions]

[libraries]
amazon_lambda_java = { module = "com.amazonaws:aws-lambda-java-core", version = "1.2.3" }
spring_cloud_function_adapter = { module = "org.springframework.cloud:spring-cloud-function-adapter-aws", version = "4.2.2" }

[plugins]
graalvm-build-plugin = { id = "org.graalvm.buildtools.native", version = "0.10.6" }
